### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by dennisjomara** [cdaringe/clean-air-for-all-now#13]
We need to add a "donate' button

**Comment by cdaringe** [comment]
<img width="47" alt="Screen Shot 2022-05-13 at 5 59 38 PM" src="https://user-images.githubusercontent.com/1003261/168404899-6ad65730-8be7-4cc7-85aa-68b35ad023b9.png">
Here's a photo i've uploaded :) Just dragged and dropped right into the text box!

**Comment by dennisjomara** [comment]
![IntelSurroundingCommunitiesGoogleEarth](https://user-images.githubusercontent.com/105460454/168405202-6cb2ce58-1c88-4aec-bf2d-b8afd26caacd.jpg)

**Comment by cdaringe** [comment]
christopher.dieringer@gmail.com

**Comment by dennisjomara** [comment]
Most everything done so far looks good. Here are a few adjustments/additions, etc.
1. Under Chemical of the Month: Hydrogen Fluoride, the second half of the text beginning with "Intel NM uses and emits a wide variety of ...." needs to be what appears when someone clicks Chemical of the Month. Then beneath that would be links to each monthly chemical. At present, we just have Hydrogen Fluoride but I will soon send you new ones for April and May and monthly ones after that.
2. We would like to have a second photo on the home page. It's an aerial view of the Intel NM plant showing the dense residential development around the plant. The caption would be "This aerial photo shows the dense residential development surrounding the Intel NM plant." I will send that to you.
3. We need a "Donate" button and Greg will have to share with you the linkage to our GoFundMe page.
4. Once these items are addressed, the site can go live. After that, I will be sending additional material including chemicals of the month, monthly newsletters, media articles and scientific studies. Over time, we will want to eliminate some material that is outdated. In addition, we will want to occasionally change the "Feature Article" that appears on the home page. I was thinking so as not to constantly bug you, perhaps we could agree on one or two days a month such as the 1st and 15th for me to routinely send new material for posting or to request old material to delete. On rare occasion though, if we have something urgent, I would want to ask for that to be posted immediately regardless of day-of-the-month. Please let me know what you think.

Dennis

**Comment by cdaringe** [comment]
> Under Chemical of the Month: Hydrogen Fluoride, the second half ...

Done. Please confirm

> We would like to have a second photo on the home page.

Photo added

> We need a "Donate" button and Greg will have to share with you the linkage to our GoFundMe page.

Still workin on this one

**Comment by dennisjomara** [comment]
Second Photo: Good !

Chemical of the Month: Still an issue. Let's start over and eliminate what is there now. I think we can keep it simple by not including the introductory information. So I will send you the three chemicals of the month to post for March, April and May - Hydrogen Fluoride, Arsine, and Phosphine respectively. Gracias.

Dennis

**Comment by dennisjomara** [comment]
Hi Chris. Just checking in to see where we stand on finishing off those last few items on our CAFA-now website. I imagine the Donate button is the tricky part. 

Dennis

**Comment by cdaringe** [comment]
> donate button

still pending for info from Greg

> Chemical of the Month: Still an issue

It’s still not clear to me what is desired after reading your remark. I’ve done a few iterations here. at this point, a spec or visual mock up is probably worthwhile

**Comment by dennisjomara** [comment]
So I take it that the Chemical of the Month is the confusing issue. What I was originally thinking is that when someone clicked on Chemical of the Month, what would appear is the text of the introductory paragraph with links to each of the chemicals of the month below the text. So It would have looked like this.

Intel Chemical of the Month

Intel New Mexico uses and emits a wide variety of chemicals, many of which are toxic and present a danger to human health and to the environment. CAFA-now leadership has added this Chemical-of-the Month feature to our website because we believe that those living near the Intel plant need to know as much as possible about individual chemicals that Intel emits. Etc, Etc.

March Intel Chemical of the Month: Hydrogen Fluoride 
April Intel Chemical of the Month: Arsine
May Intel Chemical of the Month: Phosphine

But the introductory material got mixed in with the March chemical of the month. After further consideration, I think it best to totally eliminate the introductory material and just post the individual chemicals of the month. So it would look like this.

Intel Chemical of the Month

March Intel Chemical of the Month: Hydrogen Fluoride 
April Intel Chemical of the Month: Arsine
May Intel Chemical of the Month: Phosphine

Please let me know if this responds to your question, or if not, what other clarification I need to provide. Thanks,

Dennis

**Comment by cdaringe** [comment]
Update, still missing donation info. I have free time today if we can get it!

**Comment by dennisjomara** [comment]
Assume you are waiting on Greg to provide that info. Wish we had it but unfortunately, we don’t. Thanks for keeping after it.

Dennis

**Comment by cdaringe** [comment]
Donate button added:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1003261/173208826-29a72e3b-cd41-4b23-9296-7358c21d940b.png">

**Comment by cdaringe** [comment]
Chemical of then month content simplified, per request

**Comment by cdaringe** [comment]
Moving the CoM questions to the CoM thread. closing as the donate button/link is done
